export enum Routes {
  App = "app",
  Home = "home",
  Auth = "auth",
  Recipe = "recipe",
  SignIn = "sign-in",
  SignUp = "sign-up",
  Profile = "profile",
  Security = "security",
  Settings = "settings",
  AddRecipe = "add-recipe",
  ContactUs = "contact-us",
  EditRecipe = "edit-recipe",
  ConfirmCode = "confirm-code",
  Notification = "notification",
  SavedRecipes = "saved-recipes",
  AuthorProfile = "author-profile",
  ResetPassword = "reset-password",
  ForgotPassword = "forgot-password",
}
