export enum Routes {
  App = "app",
  Home = "home",
  Auth = "auth",
  Recipe = "recipe",
  SignIn = "sign-in",
  SignUp = "sign-up",
  Offline = "offline",
  Profile = "profile",
  Security = "security",
  Settings = "settings",
  AddRecipe = "add-recipe",
  EditRecipe = "edit-recipe",
  Notification = "notification",
  SavedRecipes = "saved-recipes",
  AuthorProfile = "author-profile",
}
