#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check ESLint Standards
npm run lint ||
(
        echo '❌ ESLint Check Failed 
                Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run ts ||
(
    echo '❌ Failed Type check.
            Make the changes required above.'
    false;
)

git add .

# If everything passes... Now we can commit
echo '✅✅✅✅ You have won... I am committing this now. ✅✅✅✅'